steps:
  # Build the Docker image using the Dockerfile in the current directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-spring-app-repo/my-spring-app:latest'
      - '.'

  # Push the tagged Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-spring-app-repo/my-spring-app:latest'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-spring-service'  # You can change the service name if you wish
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/my-spring-app-repo/my-spring-app:latest'
      - '--region=us-central1' # Match the region of your Artifact Registry repo
      - '--platform=managed'
      - '--quiet'
      # CRITICAL for /experimental folder: Ingress must be internal.
      - '--ingress=internal'
      # Note: --allow-unauthenticated is not permitted in the /experimental folder.

# List the images to be built and pushed
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-spring-app-repo/my-spring-app:latest'